apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: ingress-nginx
spec:
  environments:
    dev01:
      defaultNamespace: dev
      server: https://130.193.34.162:6443
    dev02:
      defaultNamespace: dev
      server: https://130.193.34.162:6443
    prod01:
      defaultNamespace: prod
      server: https://51.250.17.75:6443
    prod02:
      defaultNamespace: prod
      server: https://51.250.17.75:6443
  vars:
    computed:
      - name: ingressNginx
        code: |
          {
            local p = (import './params.libsonnet').components.ingressNginx,
            command: 'sh',
            args: [
              '-c',
              ('/opt/homebrew/bin/helm template "${__DS_NAME__}" "${__DS_PATH__}" -n test -f-')
            ],
            stdin: std.manifestJson(p.values),
          }
  dataSources:
    - exec://ingress-nginx?configVar=ingressNginx

